# Generated by Django 5.2 on 2025-04-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_menu_order_orderitem_outlet_menu_outlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image_url',
            field=models.URLField(blank=True, default='https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQKfg7N2USWzRLIVY11-cCspadChLECuuhy7RBhe-_CfVv8Fw0o9bgJmNQozQLLLubb1vYlUQ', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='image_url',
            field=models.URLField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROdV0NHChvD7euSYRG-Y6bgwmFVPn_5A2suA&s', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='location',
            field=models.CharField(default='no location provided', max_length=255),
        ),
    ]
