# Generated by Django 5.2 on 2025-04-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_menu_image_url_alter_outlet_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='preparation_time',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
