# Generated by Django 5.2 on 2025-04-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_menu_preparation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('picked', 'Picked'), ('prepared', 'Prepared')], default='pending', max_length=10),
        ),
    ]
